plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'org.cadixdev.licenser' version '0.6.1'
}

group 'me.lucko.luckperms'
version '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

license {
    header = file('HEADER.txt')
    include '**/*.java'
    newLine = true
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.slf4j:slf4j-api:1.7.36'
    compileOnly 'net.luckperms:api:5.5'
    implementation 'io.javalin:javalin:6.7.0'
    implementation 'io.javalin.community.openapi:javalin-swagger-plugin:6.7.0-5'
}

shadowJar {
    archiveFileName = "luckperms-rest-api-v1.jar"
}

artifacts {
    archives shadowJar
}